### ISSUE TITLE
Undefined index on line 150

### ISSUE THREAD

**Issue by SilkAndSlug** [petitssuisses/piwigo-ForceHTTPS#7]
Notice: Undefined index: force_https in /var/www/my-site/plugins/Force_HTTPS/main.inc.php on line 150

ForceHTTPS v2.0.0

**Comment by SilkAndSlug** [comment]
This is fixed in v2.0.1. Please mark fixed.

**Comment by HazardyKnusperkeks** [comment]
I had the same issue after an update. I don't know to which version it was updated, but I had to manually delete the plugin in the filesystem.

After a remove and reinstall in piwigo everything worked again. Maybe there is a bug in the update procedure?
