### ISSUE TITLE
Infinite redirect

### ISSUE THREAD

**Issue by SilkAndSlug** [petitssuisses/piwigo-ForceHTTPS#8]
ForceHTTPS appears to conflict with my vhost's redirect. Presumably ForceHTTPS defaults to redirecting to HTTP -- not HTTPS -- which my vhost then redirects to HTTPS. The vhost's redirect works fine; I use it for multiple sites, and have been using on this site for months. 

Deleting the ./plugins/Force_HTTPS/ directory fixed the problem.

For reference, this is in my vhost file (Centos 6, Apache/2.2.15):

    <VirtualHost *:80>
        ServerName example.com

        # require HTTPS
        Redirect permanent / https://example.com/
    </VirtualHost>

**Comment by petitssuisses** [comment]
Sure, I may add an activation button to avoid redirecting by default (and will). But why do you need the plugin if you already have your http traffic redirected to https?

**Comment by SilkAndSlug** [comment]
@petitssuisses : I don't need the plugin -- hence I deleted the files. 

FYI. I installed the plugin 12th April, 2016, as part of installing Piwigo on that vhost, but didn't configure it. I wasn't aware of the plugin doing anything. I added the redirection to the vhost (on 21th September, 2017) as part of a "HTTPS-everywhere" project, so I know the two co-existed from that date until this.

**Comment by petitssuisses** [comment]
OK thanks ! I implemented redirect to http with the new partial https in the latest version (starting 2.0.0). Maybe it occured until you updated it. I'll implement a switch to prevent this. Again, thanks for the info

**Comment by petitssuisses** [comment]
Should be fixed in last commit.
